// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDgw6WRc7Q2MIAnBDNY43NW4cNLvopreTU',
//     appId: '1:9987698489:web:b3271346f560676d6282e8',
//     messagingSenderId: '9987698489',
//     projectId: 'showmaker-fdde8',
//     authDomain: 'showmaker-fdde8.firebaseapp.com',
//     storageBucket: 'showmaker-fdde8.appspot.com',
//     measurementId: 'G-BFHPVCMQ1B',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD2KLV9ZUXlvpNilcVBXZMAJOZtEU44zDQ',
//     appId: '1:9987698489:android:3fa67a458fee10e86282e8',
//     messagingSenderId: '9987698489',
//     projectId: 'showmaker-fdde8',
//     storageBucket: 'showmaker-fdde8.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAfxxvmvOL5nrsfWwxpCbJ8AO1GYA63OEE',
//     appId: '1:9987698489:ios:c7db639603a97dd76282e8',
//     messagingSenderId: '9987698489',
//     projectId: 'showmaker-fdde8',
//     storageBucket: 'showmaker-fdde8.appspot.com',
//     iosClientId:
//         '9987698489-sc6pa8o73neutv12rhnqgil4mc8p1h4d.apps.googleusercontent.com',
//     iosBundleId: 'com.example.showmaker',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAfxxvmvOL5nrsfWwxpCbJ8AO1GYA63OEE',
//     appId: '1:9987698489:ios:9a6636b5ee4bf97f6282e8',
//     messagingSenderId: '9987698489',
//     projectId: 'showmaker-fdde8',
//     storageBucket: 'showmaker-fdde8.appspot.com',
//     iosClientId:
//         '9987698489-hvti8fl04rcbsghhcddsdhare259tfcu.apps.googleusercontent.com',
//     iosBundleId: 'com.example.showmaker.RunnerTests',
//   );
// }
