// // // File generated by FlutterFire CLI.
// // // ignore_for_file: type=lint
// // import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// // import 'package:flutter/foundation.dart'
// //     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// // /// Default [FirebaseOptions] for use with your Firebase apps.
// // ///
// // /// Example:
// // /// ```dart
// // /// import 'firebase_options.dart';
// // /// // ...
// // /// await Firebase.initializeApp(
// // ///   options: DefaultFirebaseOptions.currentPlatform,
// // /// );
// // /// ```
// // class DefaultFirebaseOptions {
// //   static FirebaseOptions get currentPlatform {
// //     if (kIsWeb) {
// //       return web;
// //     }
// //     switch (defaultTargetPlatform) {
// //       case TargetPlatform.android:
// //         return android;
// //       case TargetPlatform.iOS:
// //         return ios;
// //       case TargetPlatform.macOS:
// //         return macos;
// //       case TargetPlatform.windows:
// //         return windows;
// //       case TargetPlatform.linux:
// //         throw UnsupportedError(
// //           'DefaultFirebaseOptions have not been configured for linux - '
// //           'you can reconfigure this by running the FlutterFire CLI again.',
// //         );
// //       default:
// //         throw UnsupportedError(
// //           'DefaultFirebaseOptions are not supported for this platform.',
// //         );
// //     }
// //   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCVB-Mp210dlFSI3hg8oQ0vNzUY2c9oUgk',
//     appId: '1:9987698489:web:487c547355ee2ec66282e8',
//     messagingSenderId: '9987698489',
//     projectId: 'showmaker-fdde8',
//     authDomain: 'showmaker-fdde8.firebaseapp.com',
//     storageBucket: 'showmaker-fdde8.appspot.com',
//     measurementId: 'G-8CLT1S7DT9',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD2KLV9ZUXlvpNilcVBXZMAJOZtEU44zDQ',
//     appId: '1:9987698489:android:1e7c2b931867a2c86282e8',
//     messagingSenderId: '9987698489',
//     projectId: 'showmaker-fdde8',
//     storageBucket: 'showmaker-fdde8.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAfxxvmvOL5nrsfWwxpCbJ8AO1GYA63OEE',
//     appId: '1:9987698489:ios:fc11a81899e8b4d36282e8',
//     messagingSenderId: '9987698489',
//     projectId: 'showmaker-fdde8',
//     storageBucket: 'showmaker-fdde8.appspot.com',
//     androidClientId: '9987698489-8q0aii9qpp4fqekes2jf983hlioj9mle.apps.googleusercontent.com',
//     iosClientId: '9987698489-sc6pa8o73neutv12rhnqgil4mc8p1h4d.apps.googleusercontent.com',
//     iosBundleId: 'com.example.showmaker',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAfxxvmvOL5nrsfWwxpCbJ8AO1GYA63OEE',
//     appId: '1:9987698489:ios:fc11a81899e8b4d36282e8',
//     messagingSenderId: '9987698489',
//     projectId: 'showmaker-fdde8',
//     storageBucket: 'showmaker-fdde8.appspot.com',
//     androidClientId: '9987698489-8q0aii9qpp4fqekes2jf983hlioj9mle.apps.googleusercontent.com',
//     iosClientId: '9987698489-sc6pa8o73neutv12rhnqgil4mc8p1h4d.apps.googleusercontent.com',
//     iosBundleId: 'com.example.showmaker',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCVB-Mp210dlFSI3hg8oQ0vNzUY2c9oUgk',
//     appId: '1:9987698489:web:8cff67ce52888b3e6282e8',
//     messagingSenderId: '9987698489',
//     projectId: 'showmaker-fdde8',
//     authDomain: 'showmaker-fdde8.firebaseapp.com',
//     storageBucket: 'showmaker-fdde8.appspot.com',
//     measurementId: 'G-FQWJY32J8J',
//   );
//
// // }